aded selection section
Rasoft2311/sedona pull request #2
Opened 2018-11-27 21:09 UTC by Rasoft2311

2018-11-28 14:05 UTC, vladiklem approved these changes

2018-11-28 14:05 UTC, vladiklem commented on hotels.html
> +              <legend>Стоимость в сутки(P):</legend>
Стили нужно цеплять через 'class'

2018-11-28 14:05 UTC, vladiklem commented on hotels.html
> +                  <span class="range-box">
название класса range-box по БЭМ должно быть как название элемента если ты делаешь range-box-wrap блоком и возможно лучше бы было p дать класс range-box а span range-box__wrap

2018-11-28 14:05 UTC, vladiklem commented on styles/components/select-section/output.scss
> +  legend{
Стили нужно задавать через классы , что бы понятнее почему у элемента такие стили и делать элемент reusable

2018-11-28 14:05 UTC, vladiklem commented on styles/components/select-section/output.scss
> +  input{
та же история , но тут это более оправдано

2018-11-28 14:05 UTC, vladiklem commented on styles/components/select-section/output.scss
> +  legend{
Два раза одному и тому же селектору "legend" зада1шь стили

2018-11-28 14:05 UTC, vladiklem commented on styles/components/select-section/output.scss
> +    flex-basis: 220px;
Задаёшь фиксированую ширину , по идее правильнее сделать элемент гибким

2018-11-28 14:05 UTC, vladiklem commented on styles/components/select-section/output.scss
> +  input{
опять второй раз селектору "input" задаёшь стили

2018-11-30 11:54 UTC, kryvonos-v commented on hotels.html
> +              <button class="select-section__form-range__button">Показать</button>
По БЕМу не можна робити елемент елемента, тому зміни на `select-section__range-button`

2018-11-30 12:00 UTC, kryvonos-v commented on hotels.html
> +              <label class="select-section__form-check-label">
Ти швидше всього ще десь захочеш використати checkbox і текст біля ньому. Тому я створив би для цього блок `.checkbox`, а його елементи назвавбы `.checkbox__input`, `.checkbox__icon`

2018-11-30 12:21 UTC, kryvonos-v requested changes
Вигляд для мобільних пристроїв з великими екранами:

![Вигляд для мобільних пристроїв з великими екранами](https://i.ibb.co/0q5Cq5v/Screen-Shot-2018-11-30-at-2-15-33-PM.png)

2018-12-03 13:25 UTC, kryvonos-v approved these changes

2018-12-03 15:19 UTC, merged