Added Sort section
Rasoft2311/sedona pull request #3
Opened 2018-11-29 14:17 UTC by Rasoft2311

2018-12-01 17:21 UTC, valeriiamykhalova requested changes

2018-12-01 17:21 UTC, valeriiamykhalova commented on hotels.html
> +            <h3 class="sort-section__header">Найдено:3</h3>
мені здається, що тут краще взяти цифру 3 в окремий span, але це не точно

2018-12-01 17:21 UTC, valeriiamykhalova commented on hotels.html
> +                        <input class="visually-hidden sort-fieldset__input" type="radio" name="sort" value="price" form="hotel-parametrs-form">
додай ```checked```

2018-12-01 17:21 UTC, valeriiamykhalova commented on hotels.html
> +                        <input class="visually-hidden order-fieldset__input" type="radio" name="order" value="asc" aria-label="По возрастанию" />
Вкажи форму, до якої відносяться інпути ```form="filter-hotels"```

2018-12-01 17:21 UTC, valeriiamykhalova commented on styles/components/sort-section/output.scss
> +  .sort-fieldset__name{
Не знаю на скільки виправдовують себе такі вкладення
хештег СПИТАТИ У ВОВИ

2018-12-02 18:00 UTC, vladiklem approved these changes
Лучий)

2018-12-02 18:00 UTC, vladiklem commented on styles/components/sort-section/output.scss
> +  font-size: $typography-h2;
По идеи ещё нужно указать line-height: $typography-h2 вместо стаданрартно установленного браузером.

2018-12-02 18:00 UTC, vladiklem commented on styles/main.css
> +  font-size: 0.75rem;
Размеры шрифтов лучше указывать через переменные.

2018-12-03 12:05 UTC, kryvonos-v commented on hotels.html
> +            <h3 class="sort-section__header">Найдено:3</h3>
Це роблять у випадку, колид для цифри 3 потрібно задати окремі стилі. У іншому разі цього можна не робити.

2018-12-03 12:05 UTC, kryvonos-v commented on hotels.html
> +            <h3 class="sort-section__header">Найдено:3</h3>
І ще перед цифрою 3 постав пробіл ;)

2018-12-03 12:07 UTC, kryvonos-v commented on hotels.html
> +                        <svg class="order-fieldset__arrow" xmlns="http://www.w3.org/2000/svg" width="11" height="10"><path fill="#cacaca" d="M5.5 0L0 10h11z"/></svg>
Коли svg вставляєш на пряму у html документ, то атрибут `xmlns="http://www.w3.org/2000/svg"` можна видалити

2018-12-03 12:09 UTC, kryvonos-v commented on hotels.html
> +                    <label class="order-fieldset__label widescreen-mr-10">
Стосовно утиліт виду `widescreen-mr-10`, нам потрібно буде узгодити у який спосіб ми показуємо, що вона діє для екранів певного розміру, тобто:
`widescreen-mr-10`, або `widescreen:mr-10`.
Мені подобається другий варіант

2018-12-03 12:11 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +  .sort-fieldset__name{
#askvova :)

2018-12-03 12:17 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +  .sort-fieldset__name{
У даному випадку немає змісту робити вкладення. І взагалі пам'ятайте що селектори з вкладення збільшують вагу селектора, що у свою чергу може призвести до проблем у майбутньому. Тобто селектор `.sort-fieldset .sort-fiedlset__name`, має більшу вагу ніж селектор `.sort-fiedlset__name`.
Відповідно, якщо задані стилі типу:
```css
.sort-fieldset .sort-fiedlset__name {
  text-align: center;
}

.sort-fiedlset__name {
  text-align: left;
}
```
то стилі селектора `.sort-fieldset .sort-fiedlset__name`, перезапишуть стилі `.sort-fiedlset__name`. Тоді нам щоб перевизначити стилі для `.sort-fieldset .sort-fiedlset__name`, потрібно буде городити якісь костилі типу:
```css
.sort-fiedlset__name {
  text-align: left !important;
}
```

2018-12-03 12:20 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +    .sort-fieldset__type{
Тут вкладення виправдане за рахунок того, що стилі класу `.sort-fieldset__type` залежать від того активний чи елемент з класом `.sort-fieldset__label`.
Тобто у даному випадку за рахунок вкладення ми показали залженість між класами

2018-12-03 12:25 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +  .sort-fieldset__name{
І взагалі краще писати не:
```scss
.sort-fieldset {
  .sort-fiedlset__name {
    /* your styles */
  }
}
```
, а:
```css
.sort-fieldset .sort-fiedlset__name { /* your styles */ }
```
Останній підхід вимагає дублювати назви класу `sort-fieldseе`, але з іншої сторони це покращує читабельність коду. І взагалі це один з тих випадків коли ми надаємо перевагу дублюваню заради кращої чатабельності. Тобто ми ігноруємо принцип **DRY** (Don't repeat yourself)

2018-12-03 12:31 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +  .sort-section__header{
Ти тут використовуєш CSS'вий підхід до написання стилів в залежності від розміру екранів. Тобто ти визначаєш стилі під різні екрани у різних місцях, тому замість того щоб писати:
```scss
.sort-section__header{
  color:$color-primary-text;
  font-size: $typography-h2;
  font-weight: bold;
  text-transform: uppercase;
}

@include mobile{
  .sort-section__header {
    margin-bottom: 10px;
    flex-basis: 100%;
  }
}

@include tablet {
  .sort-section__header {
    margin-right: 50px;
  }
}
```
краще написати:
```scss
.sort-fieldset__header {
color:$color-primary-text;
  font-size: $typography-h2;
  font-weight: bold;
  text-transform: uppercase;

  @include mobile {
  margin-bottom: 10px;
    flex-basis: 100%;
  }

  @include tablet {
    margin-right: 50px;
  }
}
```

2018-12-03 12:39 UTC, kryvonos-v commented on styles/main.css
> +  font-size: 0.75rem;
Влад, це просто вже скомпільовані стилі))

2018-12-03 12:44 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +.sort-fieldset{
Зараз у тебе стилі БЕМ блоку `.sort-fieldset` лежать у файлі `styles/components/sort-section/output.scss`. Це поганий підхід за рахунок того, що потім ці стилі буде важко знайти людині яка, хоче прочитати твій код. Бо тільки ти знаєш, що стилі блоку `.sort-fieldset` знаходиться у файлі `styles/components/sort-section/output.scss`. Швидше всього ти і сам через деякий час забудш у якому файлі у тебе заходяться ті стилі. Тому важливо для кожного БЕМ блоку створювати окремий файл

2018-12-03 12:58 UTC, kryvonos-v requested changes
:)

2018-12-03 12:58 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +.order-fieldset{
Це БЕМ блок теж потрібно винести в окремий клас

2018-12-03 12:58 UTC, kryvonos-v commented on styles/components/sort-section/output.scss
> +  flex-grow: 1;
Ми не задаємо для БЕМ блоку CSS властивості, які відповідають за зовнішнюю геометрію: `margin`, `position: absolute`, `flex-grow`.
Тому додай ті стилі або через CSS утиліту `.flex-grow`, або як БЕМ елемент `.sort-section__sort-fieldset`

2018-12-03 15:19 UTC, merged